### ISSUE TITLE
No metadata available when installing #r.area.createweight addon for GRASS GIS 

### ISSUE THREAD

**Issue by naufalianf** [tgrippa/Dasymetric_mapping_using_GRASSGIS#1]
Hello,
Currently im struggling when installing #r.area.createweight add on for my GRASS GIS, error always appear as down below in GRASS GIS 7.8.3, 7.8.7, 8.0.1

Please, give your advice, if there any solution for this

WARNING: No metadata available for module 'r.area.createweight': Unable to
         fetch interface description for command '<r.area.createweight>'.

         Details: <Cannot find the executable r.area.createweight>
ERROR: Unable to read manual page: [Errno 2] No such file or directory:
       'C:\\Users\\*in\\AppData\\Roaming\\GRASS8\\addons\\docs\\html\\r.area.createweight.html'

![errorGRASS](https://user-images.githubusercontent.com/90570415/165038998-de33873a-d430-4131-b282-656e32c7ae53.PNG)

Thank you!

**Comment by tgrippa** [comment]
Hi @naufalianf and thank you for reporting. 
This issue is not related to this repository. For issues with GRASS GIS add-on, you have to raise an issue on GRASS GIS ADDON repo. 

=> The open issue is here: https://github.com/OSGeo/grass-addons/issues/739
